### ISSUE TITLE
TFTP Not Enabled By Default 

### ISSUE THREAD

**Issue by SpicyITC** [jasonbuechler/asus-rebadger#1]
The TFTP client is not enabled by default on Windows 10. I didn't have it on, so I puzzled at the error:
Immediately executing TFTP transfer to 192.168.29.1 ...
tftp : The term 'tftp' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At D:\Users\Paul\Desktop\ASUS\the-badger-v2.4.0\bits\TFTP flash old Tmo FW via subnet 29.ps1:8 char:1
+ tftp -i $gw put TM-AC1900_3.0.0.4_376_1703-g0ffdbba.trx

The script could use Powershell to confirm that the TFTP client is enabled. If not, enable it.
https://www.ghacks.net/2017/07/14/use-windows-powershell-to-install-optional-features/

Or provide steps to use the Windows GUI to enable the client.

**Comment by jasonbuechler** [comment]
Wow, it looks like you found a regression in my code that's existed since leaving v1.0.0 behind!  The relevant code to check the current tftp state is actually still in the current codebase but it looks like i butterfingered a copy/paste and lost lines 90-104 from v1 which enabled tftp if it found it wasn't enabled. (see https://github.com/jasonbuechler/asus-rebadger/blob/master/v100/badger.ps1 ... I knew i kept it around for a reason)

thanks for the heads up!! i'll fix this up later today!

**Comment by jasonbuechler** [comment]
Ok it's back in the current codebase :D
Thanks also for the idea to provide users instructions to manually do it, in case the automatic enabling doesn't work -- that's in there now too 👍

**Comment by SpicyITC** [comment]
Sorry for the delayed reply. Again frustrated by what should be easy. But that's the "fun" of hacking IT gear.

I tried your new Badger code a few times and still had the connection error. I checked Slickdeals and saw the router was available again for $40. So I ordered one. So when that one comes in, I can test the Badger against a fresh one.

But I did some more Googling on the firmware error message. I found the "hack" you talked about. After dealing with a USB key that wouldn't mount, I'm having an SSL error during the wget.

I'm bouncing between projects, so I'll bounce back to the USB key hack when I can. And when the new router comes I'll try the Badger again.

Cheers,
PT





---- On Tue, 07 May 2019 18:39:22 -0700 jasonbuechler <mailto:notifications@github.com> wrote ----


Ok it's back in the current codebase :D
 Thanks also for the idea to provide users instructions to manually do it, in case the automatic enabling doesn't work -- that's in there now too 👍

**Comment by jasonbuechler** [comment]
Hey no problem at all -- I'm just (a little too) excited to encounter someone who's having these issues "in the wild" who also is tech savvy and willing to help!  Regarding your SSL error, I'm totally just winging a guess here, but what was the output of this command from the infamous "google doc guide"?

> validForm = function(){document.form.SystemCmd.value = "ping\nwget -A txt -r -nH -nd --no-check-certificate mywebsite.com";return true;}

I only just learned about this google doc thing yesterday, so I'm not aware what the "(No more SSL error)" mention is within it, but I'm going to wager a guess it had to do with certificate auth.

Again if you do regain access to your router, I'd love if you could archive everything and anything, please and thank you :D I'm not sure who the secret club is (besides docbill) who've been discussing the exploits behind the scenes of this google doc, so I'm not sure who else might have the crippled tmo files. :p 

A word of note -- if you haven't done so already, definitely work on some way to block the router from phoning home... the latest Merlin firmware actively removes "\n" from the ping queries trick. I'm guessing that's because asus now checks for that in its most recent firmware... meaning even more exotic exploits will be necessary soon, perhaps.

**Comment by jasonbuechler** [comment]
Looks like we started discussing this stuff in Issue #2 and since we fixed this regression (in version 2.4 or 2.5, I think), I figure we can close this issue. :D
